export const categories = {
  standard_categories: [
    {
      id: 23,
      full_name: "grass",
      name: "grass",
      description: "Grass",
      created_at: "2023-10-04T07:52:21.794106Z",
      publised: false,
      view_name: "grass",
      is_display: true,
      is_deleted: false,
      project: 1,
      global_standard_category: 5,
    },
    {
      id: 24,
      full_name: "trees",
      name: "trees",
      description: "trees",
      created_at: "2023-10-04T09:54:56.420962Z",
      publised: false,
      view_name: "trees",
      is_display: true,
      is_deleted: false,
      project: 1,
      global_standard_category: 6,
    },
  ],
  sub_categories: [
    {
      id: 12,
      full_name: "grass | green",
      standard_category_name: "grass",
      name: "green",
      description: "grass - green",
      created_at: "2023-10-04T08:13:23.469625Z",
      publised: false,
      view_name: "grass | green",
      is_display: true,
      is_deleted: false,
      project: 1,
      standard_category: 23,
      global_standard_category: 5,
      global_sub_category: 7,
    },
    {
      id: 14,
      full_name: "grass | red",
      standard_category_name: "grass",
      name: "red",
      description: "grass -red",
      created_at: "2023-10-04T09:55:30.069247Z",
      publised: false,
      view_name: "grass | red",
      is_display: true,
      is_deleted: false,
      project: 1,
      standard_category: 23,
      global_standard_category: 5,
      global_sub_category: 8,
    },
  ],

  categories_measuring: [
    {
      id: 5,
      full_name: "grass | green | short",
      name: "short",
      description: "grass-green-short",
      created_at: "2023-10-04T08:44:09.060654Z",
      publised: false,
      view_name: "grass | green | short",
      is_display: true,
      is_deleted: false,
      project: 1,
      standard_category: 23,
      global_standard_category: 5,
      sub_category: 12,
      global_sub_category: 7,
      global_category: 11,
    },
    {
      id: 6,
      full_name: "grass | green | tall",
      name: "tall",
      description: "grass-green-tall",
      created_at: "2023-10-04T09:51:42.129861Z",
      publised: false,
      view_name: "grass | green | tall",
      is_display: true,
      is_deleted: false,
      project: 1,
      standard_category: 23,
      global_standard_category: 5,
      sub_category: 12,
      global_sub_category: 7,
      global_category: 8,
    },
    {
      id: 7,
      full_name: "grass | red | tall",
      name: "tall",
      description: "grass-red-tall",
      created_at: "2023-10-04T09:55:48.366157Z",
      publised: false,
      view_name: "grass | red | tall",
      is_display: true,
      is_deleted: false,
      project: 1,
      standard_category: 23,
      global_standard_category: 5,
      sub_category: 14,
      global_sub_category: 8,
      global_category: 9,
    },
  ],
};
